#!/bin/bash
# =============================================================================
#  Home Network Security Audit — Linux Firewall Hardening
#  Script: firewall_hardening.sh
#  Author: [Your Name]
#  Description: Applies UFW + iptables rules to harden a Linux host
#               based on common home network audit findings.
#
#  ⚠ WARNING: Review all rules before applying.
#              Run on a test machine first.
#              Incorrectly applied rules can lock you out of SSH.
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ─── Root Check ───────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}[ERROR] This script must be run as root.${NC}"
    echo "  Usage: sudo ./firewall_hardening.sh"
    exit 1
fi

# ─── Trusted SSH IP (set this before running!) ───────────────────────────────
TRUSTED_SSH_IP="${TRUSTED_SSH_IP:-192.168.1.0/24}"

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════╗"
echo "║     LINUX FIREWALL HARDENING SCRIPT             ║"
echo "║     Home Network Security Audit                  ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "${YELLOW}[!] Trusted SSH range: ${BOLD}${TRUSTED_SSH_IP}${NC}"
echo -e "${YELLOW}[!] Starting in 5 seconds... Press Ctrl+C to abort${NC}"
sleep 5

# ─── Install UFW if needed ───────────────────────────────────────────────────
if ! command -v ufw &> /dev/null; then
    echo -e "${CYAN}[*] Installing UFW...${NC}"
    apt-get update -qq && apt-get install -y ufw
fi

echo ""
echo -e "${GREEN}[Step 1/7] Resetting UFW to defaults...${NC}"
ufw --force reset
ufw --force disable

echo -e "${GREEN}[Step 2/7] Setting default policies...${NC}"
ufw default deny incoming   # Block all inbound by default
ufw default allow outgoing  # Allow all outbound
ufw default deny forward    # Block forwarding
echo -e "  → Default DENY incoming, ALLOW outgoing"

echo -e "${GREEN}[Step 3/7] Allowing loopback interface...${NC}"
ufw allow in on lo
ufw allow out on lo

echo -e "${GREEN}[Step 4/7] Restricting SSH access...${NC}"
# Allow SSH only from trusted local network
ufw allow from "$TRUSTED_SSH_IP" to any port 22 proto tcp comment "SSH from trusted network"
# Rate-limit SSH to prevent brute-force
ufw limit ssh comment "SSH rate limit"
echo -e "  → SSH allowed only from: ${BOLD}${TRUSTED_SSH_IP}${NC}"

echo -e "${GREEN}[Step 5/7] Blocking critical vulnerable ports...${NC}"
BLOCK_PORTS=(
    "21:FTP - Unencrypted file transfer"
    "23:Telnet - Unencrypted remote access"
    "135:MS-RPC - Windows RPC exploitation"
    "137:NetBIOS-NS - Windows legacy protocol"
    "138:NetBIOS-DGM - Windows legacy protocol"
    "139:NetBIOS-SSN - SMB over NetBIOS"
    "445:SMB - EternalBlue/ransomware target"
    "1433:MSSQL - Database never exposed"
    "1434:MSSQL-UDP - Database browser"
    "3306:MySQL - Database never exposed"
    "3389:RDP - Remote Desktop brute-force target"
    "5900:VNC - Weak authentication"
    "5800:VNC-HTTP - Web-based VNC"
    "6881:BitTorrent - P2P"
    "6667:IRC - Often used by botnets"
)

for entry in "${BLOCK_PORTS[@]}"; do
    PORT="${entry%%:*}"
    DESC="${entry#*:}"
    ufw deny in "$PORT" comment "$DESC" 2>/dev/null || true
    echo -e "  → Blocked port ${BOLD}${PORT}${NC} (${DESC})"
done

echo -e "${GREEN}[Step 6/7] Enabling logging...${NC}"
ufw logging on
ufw logging medium
echo -e "  → Firewall logs enabled (check: /var/log/ufw.log)"

echo -e "${GREEN}[Step 7/7] Enabling UFW...${NC}"
ufw --force enable
echo ""

# ─── Bonus: Kernel Network Hardening (sysctl) ─────────────────────────────────
echo -e "${CYAN}[+] Applying kernel network hardening (sysctl)...${NC}"

SYSCTL_FILE="/etc/sysctl.d/99-security-hardening.conf"

cat > "$SYSCTL_FILE" << 'EOF'
# ──────────────────────────────────────────────
#  Network Security Hardening — sysctl settings
#  Generated by: Home Network Security Audit
# ──────────────────────────────────────────────

# Disable IP forwarding (not a router)
net.ipv4.ip_forward = 0

# Ignore ICMP broadcast pings
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# Enable TCP SYN cookies (SYN flood protection)
net.ipv4.tcp_syncookies = 1

# Do not accept ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Ignore bogus ICMP errors
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable reverse path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1

# Disable IPv6 if not needed
# net.ipv6.conf.all.disable_ipv6 = 1
EOF

sysctl --system > /dev/null 2>&1
echo -e "  → Kernel hardening applied: ${SYSCTL_FILE}"

# ─── Bonus: Install fail2ban ──────────────────────────────────────────────────
if command -v apt-get &> /dev/null; then
    echo -e "${CYAN}[+] Installing fail2ban (brute-force protection)...${NC}"
    apt-get install -y fail2ban -qq

    cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 5

[sshd]
enabled = true
port    = ssh
logpath = %(sshd_log)s
backend = %(syslog_backend)s
EOF

    systemctl enable fail2ban --quiet
    systemctl restart fail2ban
    echo -e "  → fail2ban enabled (SSH brute-force protection active)"
fi

# ─── Final Status ─────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  HARDENING COMPLETE${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo ""
ufw status verbose
echo ""
echo -e "${GREEN}  ✓ Firewall is active and hardened${NC}"
echo -e "${GREEN}  ✓ Kernel sysctl parameters applied${NC}"
echo -e "${GREEN}  ✓ fail2ban protecting SSH${NC}"
echo ""
echo -e "${YELLOW}  Logs: /var/log/ufw.log${NC}"
echo -e "${YELLOW}  View rules: sudo ufw status numbered${NC}"
echo ""
